var quintiles = {
  "Q1": [
    "Afghanistan",
    "Angola",
    "Bangladesh",
    "Benin",
    "Bhutan",
    "Burkina Faso",
    "Burundi",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Egypt",
    "Ethiopia",
    "The Gambia",
    "Guinea",
    "Guinea-Bissau",
    "Haiti",
    "India",
    "Liberia",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mozambique",
    "Nepal",
    "Niger",
    "Nigeria",
    "Pakistan",
    "Papua New Guinea",
    "Senegal",
    "Sierra Leone",
    "South Sudan",
    "Sudan",
    "Timor-Leste",
    "Togo",
    "Yemen"
  ],
  "Q2": [
    "Algeria",
    "Botswana",
    "Burma",
    "Cambodia",
    "Cameroon",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "El Salvador",
    "Eritrea",
    "Eswatini",
    "Gabon",
    "Ghana",
    "Guatemala",
    "Guyana",
    "Honduras",
    "Iran",
    "Iraq",
    "Jamaica",
    "Kenya",
    "Laos",
    "Lesotho",
    "Madagascar",
    "Morocco",
    "Nicaragua",
    "Rwanda",
    "Syria",
    "Tanzania",
    "Tunisia",
    "Uganda",
    "Vanuatu",
    "Zambia",
    "Zimbabwe"
  ],
  "Q3": [
    "Bolivia",
    "Brazil",
    "Cabo Verde",
    "Colombia",
    "Dominican Republic",
    "Ecuador",
    "Equatorial Guinea",
    "Indonesia",
    "Kuwait",
    "Lebanon",
    "Libya",
    "Malaysia",
    "Malta",
    "Mauritius",
    "Mexico",
    "Namibia",
    "Oman",
    "Palau",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Sao Tome and Principe",
    "Seychelles",
    "South Africa",
    "Sri Lanka",
    "Suriname",
    "Thailand",
    "Turkey (Turkiye)",
    "Vietnam"
  ],
  "Q4": [
    "Albania",
    "Antigua and Barbuda",
    "Argentina",
    "Aruba",
    "Bahrain",
    "Bosnia and Herzegovina",
    "Brunei",
    "Bulgaria",
    "Cayman Islands",
    "Chile",
    "China",
    "Costa Rica",
    "Czechia",
    "Gaza Strip",
    "Greece",
    "Grenada",
    "Israel",
    "Jordan",
    "South Korea",
    "Macau",
    "Maldives",
    "Marshall Islands",
    "Montenegro",
    "New Caledonia",
    "North Macedonia",
    "Romania",
    "Saudi Arabia",
    "Singapore",
    "Spain",
    "Taiwan",
    "Trinidad and Tobago",
    "United Arab Emirates",
    "Uruguay",
    "Venezuela"
  ],
  "Q5": [
    "Andorra",
    "Armenia",
    "Azerbaijan",
    "Barbados",
    "Belarus",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Estonia",
    "Fiji",
    "Georgia",
    "Greenland",
    "Hungary",
    "Italy",
    "Kazakhstan",
    "North Korea",
    "Kyrgyzstan",
    "Latvia",
    "Lithuania",
    "Moldova",
    "Mongolia",
    "Poland",
    "Russia",
    "Samoa",
    "San Marino",
    "Serbia",
    "Slovenia",
    "Tajikistan",
    "Tonga",
    "Turkmenistan",
    "Ukraine",
    "Uzbekistan"
  ]
}