var quintiles = {
  "Q1": [
    "Albania",
    "Armenia",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Estonia",
    "Finland",
    "Georgia",
    "Greece",
    "Iceland",
    "Ireland",
    "Jordan",
    "Kuwait",
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    "Libya",
    "Malta",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Oman",
    "Qatar",
    "Russia",
    "Serbia",
    "Singapore",
    "Slovenia",
    "South Korea",
    "Tajikistan",
    "Turkmenistan",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uzbekistan",
    "Vietnam"
  ],
  "Q2": [
    "Algeria",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Barbados",
    "Belarus",
    "Bhutan",
    "Brunei",
    "Canada",
    "Costa Rica",
    "Cuba",
    "Denmark",
    "Egypt",
    "Germany",
    "Hungary",
    "India",
    "Iran",
    "Iraq",
    "Israel",
    "Kazakhstan",
    "Lithuania",
    "Malaysia",
    "Maldives",
    "Mauritius",
    "Morocco",
    "New Zealand",
    "Oceania",
    "Poland",
    "Portugal",
    "Romania",
    "Saudi Arabia",
    "Slovakia",
    "Spain",
    "Sri Lanka",
    "Syria",
    "Tunisia",
    "Turkey"
  ],
  "Q3": [
    "Afghanistan",
    "Antigua and Barbuda",
    "Argentina",
    "Asia",
    "Bahamas",
    "Bangladesh",
    "Belgium",
    "Belize",
    "Cambodia",
    "Cape Verde",
    "Chile",
    "China",
    "Europe",
    "Fiji",
    "Honduras",
    "Italy",
    "Jamaica",
    "Japan",
    "Laos",
    "Micronesia (country)",
    "Myanmar",
    "Nicaragua",
    "North Korea",
    "Norway",
    "Papua New Guinea",
    "Samoa",
    "Seychelles",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Thailand",
    "Tonga",
    "Trinidad and Tobago",
    "United States",
    "Uruguay",
    "Venezuela",
    "World"
  ],
  "Q4": [
    "Brazil",
    "Cameroon",
    "Colombia",
    "Congo",
    "Cote d'Ivoire",
    "Czechia",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "El Salvador",
    "Equatorial Guinea",
    "Gabon",
    "Gambia",
    "Ghana",
    "Grenada",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Luxembourg",
    "Mexico",
    "Nepal",
    "Nigeria",
    "North America",
    "Pakistan",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Sao Tome and Principe",
    "Senegal",
    "Solomon Islands",
    "South Africa",
    "South America",
    "Togo",
    "Vanuatu",
    "Yemen"
  ],
  "Q5": [
    "Africa",
    "Angola",
    "Benin",
    "Bolivia",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Democratic Republic of Congo",
    "Djibouti",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "France",
    "Guatemala",
    "Guinea",
    "Indonesia",
    "Kenya",
    "Kiribati",
    "Lesotho",
    "Liberia",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mozambique",
    "Namibia",
    "Niger",
    "Rwanda",
    "Sierra Leone",
    "Somalia",
    "South Sudan",
    "Tanzania",
    "Uganda",
    "Zambia",
    "Zimbabwe"
  ]
}