var quintiles ={
  "Q1": [
    "Andorra",
    "Anguilla",
    "Australia",
    "Austria",
    "Belarus",
    "Belgium",
    "Bermuda",
    "Canada",
    "Cuba",
    "Czechia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "French Polynesia",
    "Germany",
    "Greece",
    "Guernsey",
    "Hong Kong",
    "Iceland",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Japan",
    "Jersey",
    "South Korea",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Portugal",
    "Singapore",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "United Kingdom",
    "Wallis and Futuna"
  ],
  "Q2": [
    "Argentina",
    "The Bahamas",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Cayman Islands",
    "Chile",
    "China",
    "Costa Rica",
    "Croatia",
    "Curacao",
    "Cyprus",
    "Faroe Islands",
    "Gibraltar",
    "Greenland",
    "Grenada",
    "Hungary",
    "Kazakhstan",
    "Kuwait",
    "Latvia",
    "Lebanon",
    "Macau",
    "Malaysia",
    "Malta",
    "Nauru",
    "New Caledonia",
    "North Macedonia",
    "Poland",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Saint Barthelemy",
    "Saint Kitts and Nevis",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "San Marino",
    "Serbia",
    "Sint Maarten",
    "Slovakia",
    "Sri Lanka",
    "Thailand",
    "Ukraine",
    "United Arab Emirates",
    "United States",
    "Uruguay"
  ],
  "Q3": [
    "Albania",
    "American Samoa",
    "Antigua and Barbuda",
    "Armenia",
    "Aruba",
    "Azerbaijan",
    "Bahrain",
    "Barbados",
    "Belize",
    "Brazil",
    "Brunei",
    "Colombia",
    "Cook Islands",
    "Dominica",
    "Ecuador",
    "El Salvador",
    "Fiji",
    "Gaza Strip",
    "Guam",
    "Iran",
    "Jamaica",
    "Jordan",
    "Libya",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Montserrat",
    "Nicaragua",
    "Northern Mariana Islands",
    "Oman",
    "Palau",
    "Panama",
    "Peru",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Saudi Arabia",
    "Seychelles",
    "Syria",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turks and Caicos Islands",
    "Vanuatu",
    "Venezuela",
    "Vietnam"
  ],
  "Q4": [
    "Algeria",
    "Bangladesh",
    "Bhutan",
    "Bolivia",
    "Botswana",
    "Cabo Verde",
    "Cambodia",
    "Republic of the Congo",
    "Dominican Republic",
    "Egypt",
    "Gabon",
    "Georgia",
    "Ghana",
    "Guatemala",
    "Guyana",
    "Honduras",
    "India",
    "Indonesia",
    "Iraq",
    "Kenya",
    "North Korea",
    "Kosovo",
    "Kyrgyzstan",
    "Maldives",
    "Marshall Islands",
    "The Federated States of Micronesia",
    "Mongolia",
    "Morocco",
    "Namibia",
    "Nepal",
    "Paraguay",
    "Philippines",
    "Rwanda",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "Samoa",
    "Senegal",
    "Solomon Islands",
    "South Africa",
    "Suriname",
    "Tajikistan",
    "Tanzania",
    "Turkey (Turkiye)",
    "Tuvalu",
    "Uganda",
    "Uzbekistan"
  ],
  "Q5": [
    "Afghanistan",
    "Angola",
    "Benin",
    "Burkina Faso",
    "Burma",
    "Burundi",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Democratic Republic of the Congo",
    "Cote d'Ivoire",
    "Djibouti",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "The Gambia",
    "Guinea",
    "Guinea-Bissau",
    "Haiti",
    "Kiribati",
    "Laos",
    "Lesotho",
    "Liberia",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mozambique",
    "Niger",
    "Nigeria",
    "Pakistan",
    "Papua New Guinea",
    "Sao Tome and Principe",
    "Sierra Leone",
    "Somalia",
    "South Sudan",
    "Sudan",
    "Timor-Leste",
    "Togo",
    "Turkmenistan",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ]
}