var quintiles = {
  "Q1": [
    "Afghanistan",
    "Africa (WHO)",
    "Cambodia",
    "Central African Republic",
    "Chad",
    "Cote d'Ivoire",
    "Democratic Republic of Congo",
    "Ethiopia",
    "Fiji",
    "Ghana",
    "Guinea-Bissau",
    "Indonesia",
    "Kiribati",
    "Land Locked Developing Countries",
    "Laos",
    "Least Developed Countries",
    "Lesotho",
    "Low-income countries",
    "Madagascar",
    "Malawi",
    "Mexico",
    "Mongolia",
    "Nepal",
    "Nigeria",
    "Sao Tome and Principe",
    "Senegal",
    "Sierra Leone",
    "Sub-Saharan Africa (SDG)",
    "Tanzania",
    "Togo",
    "Tonga",
    "Tuvalu",
    "Uganda",
    "Zimbabwe"
  ],
  "Q2": [
    "Albania",
    "Algeria",
    "Azerbaijan",
    "Bangladesh",
    "Bhutan",
    "Central and Southern Asia (SDG)",
    "Colombia",
    "Congo",
    "Dominican Republic",
    "Eastern Mediterranean (WHO)",
    "Ecuador",
    "Gambia",
    "Georgia",
    "Guatemala",
    "Honduras",
    "Iraq",
    "Lebanon",
    "Lower-middle-income countries",
    "Myanmar",
    "Nicaragua",
    "North Korea",
    "Pakistan",
    "Paraguay",
    "Peru",
    "Philippines",
    "Samoa",
    "Small Island Developing States",
    "Sri Lanka",
    "Suriname",
    "Tajikistan",
    "Turks and Caicos Islands",
    "Vietnam",
    "Wallis and Futuna",
    "World"
  ],
  "Q3": [
    "American Samoa",
    "Americas (WHO)",
    "Andorra",
    "Armenia",
    "Bosnia and Herzegovina",
    "Brazil",
    "Costa Rica",
    "Croatia",
    "Eastern and South-Eastern Asia (SDG)",
    "French Polynesia",
    "Grenada",
    "Jordan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Latin America and the Caribbean (SDG)",
    "Moldova",
    "Montenegro",
    "Morocco",
    "North Macedonia",
    "Northern Africa and Western Asia (SDG)",
    "Northern Mariana Islands",
    "Palau",
    "Palestine",
    "Poland",
    "Romania",
    "Russia",
    "Saint Helena",
    "Saint Pierre and Miquelon",
    "Serbia",
    "Tunisia",
    "Ukraine",
    "Upper-middle-income countries",
    "Uzbekistan"
  ],
  "Q4": [
    "Belarus",
    "Bulgaria",
    "Channel Islands",
    "Chile",
    "Czechia",
    "Estonia",
    "Europe (WHO)",
    "Europe and Northern America (SDG)",
    "French Guiana",
    "Greece",
    "Guadeloupe",
    "High-income countries",
    "Iran",
    "Ireland",
    "Italy",
    "Japan",
    "Latvia",
    "Lithuania",
    "Malaysia",
    "Martinique",
    "Mayotte",
    "New Caledonia",
    "Niue",
    "Norway",
    "Oman",
    "Portugal",
    "Qatar",
    "Reunion",
    "Saint Martin (French part)",
    "Slovenia",
    "Switzerland",
    "Turkmenistan",
    "United States",
    "United States Virgin Islands"
  ],
  "Q5": [
    "Austria",
    "Bahrain",
    "Belgium",
    "Bonaire, Sint Eustatius and Saba",
    "Canada",
    "Cyprus",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Gibraltar",
    "Guam",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "Isle of Man",
    "Israel",
    "Kuwait",
    "Liechtenstein",
    "Luxembourg",
    "Macao",
    "Malta",
    "Monaco",
    "Netherlands",
    "New Zealand",
    "Puerto Rico",
    "Saint Barthelemy",
    "San Marino",
    "Singapore",
    "Slovakia",
    "South Korea",
    "Spain",
    "Sweden",
    "United Kingdom"
  ]
}