var quintiles ={
  "Q1": [
    "Afghanistan",
    "Cambodia",
    "Central African Republic",
    "Chad",
    "Congo",
    "Cote d'Ivoire",
    "Democratic Republic of Congo",
    "Dominican Republic",
    "Ethiopia",
    "Fiji",
    "Ghana",
    "Guinea-Bissau",
    "Indonesia",
    "Kiribati",
    "Laos",
    "Lesotho",
    "Madagascar",
    "Malawi",
    "Mexico",
    "Mongolia",
    "Nepal",
    "Nigeria",
    "Sao Tome and Principe",
    "Senegal",
    "Sierra Leone",
    "Tanzania",
    "Togo",
    "Tonga",
    "Tuvalu",
    "Uganda",
    "Zimbabwe"
  ],
  "Q2": [
    "Albania",
    "Algeria",
    "Azerbaijan",
    "Bangladesh",
    "Bhutan",
    "Colombia",
    "Ecuador",
    "Gambia",
    "Georgia",
    "Guatemala",
    "Honduras",
    "Iraq",
    "Lebanon",
    "Morocco",
    "Myanmar",
    "Nicaragua",
    "North Korea",
    "Pakistan",
    "Paraguay",
    "Peru",
    "Philippines",
    "Samoa",
    "Sri Lanka",
    "Suriname",
    "Tajikistan",
    "Tunisia",
    "Turks and Caicos Islands",
    "Vietnam",
    "Wallis and Futuna",
    "World"
  ],
  "Q3": [
    "American Samoa",
    "Andorra",
    "Armenia",
    "Bosnia and Herzegovina",
    "Brazil",
    "Channel Islands",
    "Costa Rica",
    "Croatia",
    "French Guiana",
    "French Polynesia",
    "Grenada",
    "Jordan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Mayotte",
    "Moldova",
    "Montenegro",
    "North Macedonia",
    "Northern Mariana Islands",
    "Oman",
    "Palau",
    "Palestine",
    "Poland",
    "Romania",
    "Russia",
    "Saint Helena",
    "Saint Pierre and Miquelon",
    "Serbia",
    "Ukraine",
    "Uzbekistan"
  ],
  "Q4": [
    "Austria",
    "Bahrain",
    "Belarus",
    "Bulgaria",
    "Canada",
    "Chile",
    "Czechia",
    "Estonia",
    "Greece",
    "Guadeloupe",
    "Guam",
    "Iran",
    "Ireland",
    "Italy",
    "Japan",
    "Latvia",
    "Lithuania",
    "Malaysia",
    "Martinique",
    "New Caledonia",
    "Niue",
    "Norway",
    "Portugal",
    "Qatar",
    "Reunion",
    "Slovenia",
    "Switzerland",
    "Turkmenistan",
    "United States",
    "United States Virgin Islands"
  ],
  "Q5": [
    "Belgium",
    "Bonaire, Sint Eustatius and Saba",
    "Cyprus",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Gibraltar",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "Isle of Man",
    "Israel",
    "Kuwait",
    "Liechtenstein",
    "Luxembourg",
    "Macao",
    "Malta",
    "Monaco",
    "Netherlands",
    "New Zealand",
    "Puerto Rico",
    "Saint Barthelemy",
    "San Marino",
    "Singapore",
    "Slovakia",
    "South Korea",
    "Spain",
    "Sweden",
    "United Kingdom"
  ]
}